# Generated by Django 3.0.3 on 2020-02-19 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200205_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='particle_density',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='turbidity',
        ),
    ]
