# Generated by Django 3.0.3 on 2020-02-19 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200219_1009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurement',
            options={'ordering': ('-time',)},
        ),
    ]
