# Generated by Django 3.0.4 on 2020-03-18 01:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_measurement_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='key',
            field=models.CharField(default='0xDE72HnIrdkCC4lv9459ak4oxHeRbUYO65vNisuxhm8mInYxzO2lMt8SZ5ygXQY', max_length=64, validators=[django.core.validators.MinLengthValidator(64)]),
        ),
    ]
